workflows:
  default-workflow:
    name: Build Flutter App
    environment:
      flutter: stable

    scripts:
      - flutter pub get
      - flutter build apk --release

    artifacts:
      - build/**/outputs/**/*.apk
