// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYcVi8rNcjT_5tnrqj7yX91txBigXTEtg',
    appId: '1:52817294469:web:36ae307d3abeaca028e5ec',
    messagingSenderId: '52817294469',
    projectId: 'polleria-6ceea',
    authDomain: 'polleria-6ceea.firebaseapp.com',
    storageBucket: 'polleria-6ceea.firebasestorage.app',
    measurementId: 'G-WETZ94JBT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8gaf40EjZamSYhF9I_yVWp1Opz642Gs8',
    appId: '1:52817294469:android:5cfedf4e99f5239f28e5ec',
    messagingSenderId: '52817294469',
    projectId: 'polleria-6ceea',
    storageBucket: 'polleria-6ceea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfl2w1Tn80r9SjdY0pJmI99MjoXHI61Vk',
    appId: '1:52817294469:ios:4d9a5c07ceb2532c28e5ec',
    messagingSenderId: '52817294469',
    projectId: 'polleria-6ceea',
    storageBucket: 'polleria-6ceea.firebasestorage.app',
    iosBundleId: 'com.example.appPanaderia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfl2w1Tn80r9SjdY0pJmI99MjoXHI61Vk',
    appId: '1:52817294469:ios:4d9a5c07ceb2532c28e5ec',
    messagingSenderId: '52817294469',
    projectId: 'polleria-6ceea',
    storageBucket: 'polleria-6ceea.firebasestorage.app',
    iosBundleId: 'com.example.appPanaderia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYcVi8rNcjT_5tnrqj7yX91txBigXTEtg',
    appId: '1:52817294469:web:2510884b0150d95b28e5ec',
    messagingSenderId: '52817294469',
    projectId: 'polleria-6ceea',
    authDomain: 'polleria-6ceea.firebaseapp.com',
    storageBucket: 'polleria-6ceea.firebasestorage.app',
    measurementId: 'G-93GFV7KNSJ',
  );

}